trigger:
- main

pool:
  name: newagentpool
  demands:
    - agent.name -equals nchallahagent

variables:
  FLUTTER_HOME: /home/azureuser/myagent/sdk/flutter
  ANDROID_HOME: /home/azureuser/myagent/sdk/android-sdk
  PATH: $(PATH):$(FLUTTER_HOME)/bin:$(ANDROID_HOME)/cmdline-tools/latest/bin:$(ANDROID_HOME)/platform-tools

jobs:
- job: Build_and_Test
  displayName: 'Build and Test Flutter App'
  steps:
  
  # Step 1: Install Flutter dependencies
  - script: |
      flutter doctor
      flutter pub get
    displayName: 'Install Flutter dependencies'

  # Step 2: Run Flutter unit tests
  - script: |
      flutter test
    displayName: 'Run Flutter tests'

  # Step 3: Build the Flutter app for Android
  - script: |
      flutter build apk --release
    displayName: 'Build Flutter Android APK'

  # Step 4: Publish build artifacts (APK)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build/app/outputs/flutter-apk/app-release.apk'
      ArtifactName: 'apk'
      publishLocation: 'Container'
    displayName: 'Publish Android APK'
