


trigger:
- none

pool:
  name: newagentpool
  demands:
    - agent.name -equals nchallahagent
 

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y unzip xz-utils zip libglu1-mesa
    git clone -b master https://github.com/flutter/flutter.git
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
  displayName: 'Install Flutter'