trigger:
- none

pool:
  name: agentpoolnew
  demands:
    - agent.name -equals agentl
 

steps:
- script: |
    pwd
  displayName: 'Print Working Directory'

- script: |
    echo $ANDROID_HOME
    ls $ANDROID_HOME
  displayName: 'Check ANDROID_HOME'


- script: |
    
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub upgrade
    /home/azureuser/myagent/sdk/flutter/bin/flutter pub get
  displayName: 'pub upgrade'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'

- script: |
    ls -l
  displayName: 'is there widget ?'

- script: |
    /home/azureuser/myagent/sdk/flutter/bin/flutter test
  displayName: 'Run Tests'
  
