trigger:
- none

pool:
  name: newagentpool
  demands:
    - agent.name -equals nchallahagent

variables:
  FLUTTER_HOME: /home/azureuser/myagent/sdk/flutter
  ANDROID_HOME: /home/azureuser/myagent/sdk/android-sdk
  # Define the PATH explicitly to avoid cyclical reference issues
  CUSTOM_PATH: /home/azureuser/myagent/sdk/flutter/bin:/home/azureuser/myagent/sdk/android-sdk/cmdline-tools/latest/bin:/home/azureuser/myagent/sdk/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

jobs:
- job: Build_and_Test
  displayName: 'Build and Test Flutter App'
  steps:
  
  # Step 1: check Flutter dependencies
  - script: |
      export PATH=$(CUSTOM_PATH)
      flutter doctor
      flutter pub outdated
      flutter pub get
      
    displayName: 'Install Flutter dependencies'


  # Step 3: Build the Flutter app for Android
  - script: |
      export PATH=$(CUSTOM_PATH)
      flutter build apk --release
    displayName: 'Build Flutter Android APK'
    
  - task: FlutterTest@0 
    inputs:
     projectDirectory: './'
    displayName: 'test'



  # Step 4: Publish build artifacts (APK)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build/app/outputs/flutter-apk/app-release.apk'
      ArtifactName: 'apk'
      publishLocation: 'Container'
    displayName: 'Publish Android APK'
